/**
 * Work Orders page.
 *
 * Note: there's no AppSync resolver for FactoryMind_WorkOrders yet; this page
 * shows a stub list of static records. To wire it live, add a Query type +
 * DynamoDB resolver in infrastructure/cdk/schema/factorymind.graphql and
 * extend ml_stack.py. Tracked in tasks.md §17.2.
 */
const PLACEHOLDER = [
  {
    work_order_id: "WO-2291",
    machine_id: "CNC-AERO-08",
    priority: "CRITICAL",
    status: "OPEN",
    failure_mode: "TOOL_WEAR",
    recommended_action: "IMMEDIATE: Replace tool on CNC-AERO-08. Compound failure risk.",
    scheduled_date: "2026-05-06T19:00:00Z",
  },
  {
    work_order_id: "WO-2290",
    machine_id: "CNC-AERO-22",
    priority: "HIGH",
    status: "IN_PROGRESS",
    failure_mode: "BEARING_WEAR",
    recommended_action: "Replace end-mill on CNC-AERO-22 before next shift.",
    scheduled_date: "2026-05-07T08:00:00Z",
  },
];

export function WorkOrders() {
  return (
    <>
      <h1>Work Orders</h1>
      <p style={{ color: "var(--muted)" }}>
        Generated by Predictive Maintenance Manager. CRITICAL orders require LSTM + Lookout consensus.
      </p>
      <div className="panel">
        <table>
          <thead>
            <tr>
              <th>ID</th>
              <th>Machine</th>
              <th>Priority</th>
              <th>Status</th>
              <th>Failure Mode</th>
              <th>Action</th>
              <th>Scheduled</th>
            </tr>
          </thead>
          <tbody>
            {PLACEHOLDER.map((wo) => (
              <tr key={wo.work_order_id}>
                <td>{wo.work_order_id}</td>
                <td>{wo.machine_id}</td>
                <td className={`severity-${wo.priority}`}>{wo.priority}</td>
                <td>{wo.status}</td>
                <td>{wo.failure_mode}</td>
                <td>{wo.recommended_action}</td>
                <td>{new Date(wo.scheduled_date).toLocaleString()}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </>
  );
}
