/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardTwinRouteImport } from './routes/dashboard.twin'
import { Route as DashboardSustainabilityRouteImport } from './routes/dashboard.sustainability'
import { Route as DashboardQualityRouteImport } from './routes/dashboard.quality'
import { Route as DashboardMaintenanceRouteImport } from './routes/dashboard.maintenance'
import { Route as DashboardEdgeRouteImport } from './routes/dashboard.edge'
import { Route as DashboardAssistantRouteImport } from './routes/dashboard.assistant'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTwinRoute = DashboardTwinRouteImport.update({
  id: '/twin',
  path: '/twin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSustainabilityRoute = DashboardSustainabilityRouteImport.update({
  id: '/sustainability',
  path: '/sustainability',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQualityRoute = DashboardQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMaintenanceRoute = DashboardMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEdgeRoute = DashboardEdgeRouteImport.update({
  id: '/edge',
  path: '/edge',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAssistantRoute = DashboardAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/assistant': typeof DashboardAssistantRoute
  '/dashboard/edge': typeof DashboardEdgeRoute
  '/dashboard/maintenance': typeof DashboardMaintenanceRoute
  '/dashboard/quality': typeof DashboardQualityRoute
  '/dashboard/sustainability': typeof DashboardSustainabilityRoute
  '/dashboard/twin': typeof DashboardTwinRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/assistant': typeof DashboardAssistantRoute
  '/dashboard/edge': typeof DashboardEdgeRoute
  '/dashboard/maintenance': typeof DashboardMaintenanceRoute
  '/dashboard/quality': typeof DashboardQualityRoute
  '/dashboard/sustainability': typeof DashboardSustainabilityRoute
  '/dashboard/twin': typeof DashboardTwinRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/assistant': typeof DashboardAssistantRoute
  '/dashboard/edge': typeof DashboardEdgeRoute
  '/dashboard/maintenance': typeof DashboardMaintenanceRoute
  '/dashboard/quality': typeof DashboardQualityRoute
  '/dashboard/sustainability': typeof DashboardSustainabilityRoute
  '/dashboard/twin': typeof DashboardTwinRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/assistant'
    | '/dashboard/edge'
    | '/dashboard/maintenance'
    | '/dashboard/quality'
    | '/dashboard/sustainability'
    | '/dashboard/twin'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/assistant'
    | '/dashboard/edge'
    | '/dashboard/maintenance'
    | '/dashboard/quality'
    | '/dashboard/sustainability'
    | '/dashboard/twin'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/assistant'
    | '/dashboard/edge'
    | '/dashboard/maintenance'
    | '/dashboard/quality'
    | '/dashboard/sustainability'
    | '/dashboard/twin'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/twin': {
      id: '/dashboard/twin'
      path: '/twin'
      fullPath: '/dashboard/twin'
      preLoaderRoute: typeof DashboardTwinRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sustainability': {
      id: '/dashboard/sustainability'
      path: '/sustainability'
      fullPath: '/dashboard/sustainability'
      preLoaderRoute: typeof DashboardSustainabilityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/quality': {
      id: '/dashboard/quality'
      path: '/quality'
      fullPath: '/dashboard/quality'
      preLoaderRoute: typeof DashboardQualityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/maintenance': {
      id: '/dashboard/maintenance'
      path: '/maintenance'
      fullPath: '/dashboard/maintenance'
      preLoaderRoute: typeof DashboardMaintenanceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/edge': {
      id: '/dashboard/edge'
      path: '/edge'
      fullPath: '/dashboard/edge'
      preLoaderRoute: typeof DashboardEdgeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/assistant': {
      id: '/dashboard/assistant'
      path: '/assistant'
      fullPath: '/dashboard/assistant'
      preLoaderRoute: typeof DashboardAssistantRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAssistantRoute: typeof DashboardAssistantRoute
  DashboardEdgeRoute: typeof DashboardEdgeRoute
  DashboardMaintenanceRoute: typeof DashboardMaintenanceRoute
  DashboardQualityRoute: typeof DashboardQualityRoute
  DashboardSustainabilityRoute: typeof DashboardSustainabilityRoute
  DashboardTwinRoute: typeof DashboardTwinRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAssistantRoute: DashboardAssistantRoute,
  DashboardEdgeRoute: DashboardEdgeRoute,
  DashboardMaintenanceRoute: DashboardMaintenanceRoute,
  DashboardQualityRoute: DashboardQualityRoute,
  DashboardSustainabilityRoute: DashboardSustainabilityRoute,
  DashboardTwinRoute: DashboardTwinRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
